laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::post('newsletter', 'HomeController@newsletter')->name('newsletter');
    Route::get('busca', 'HomeController@busca')->name('busca');

    Route::get('a-america-uv/institucional', 'EmpresaController@institucional')->name('empresa.institucional');
    Route::get('a-america-uv/cd-logistico', 'EmpresaController@cdLogistico')->name('empresa.cd-logistico');
    Route::get('a-america-uv/galeria', 'EmpresaController@galeria')->name('empresa.galeria');
    Route::get('a-america-uv/galeria/{galeria_slug}', 'EmpresaController@galeriaShow')->name('empresa.galeria.show');

    Route::get('tecnologias/{categoria_slug}', 'ProdutosController@tecnologias')->name('tecnologias');
    Route::get('tecnologias/{categoria_slug}/{produto_slug}', 'ProdutosController@tecnologiasShow')->name('tecnologias.show');

    Route::get('tinta-digital-uv-led-hnd-ink', 'ProdutosController@tintas')->name('tinta-digital-uv-led-hnd-ink');
    Route::get('tinta-digital-uv-led-hnd-ink/{produto_slug}', 'ProdutosController@tintasShow')->name('tinta-digital-uv-led-hnd-ink.show');

    Route::get('materiais', 'ProdutosController@materiais')->name('materiais');
    Route::get('materiais/{produto_slug}', 'ProdutosController@materiaisShow')->name('materiais.show');

    Route::get('orcamento/{produto_slug}', 'ProdutosController@orcamento')->name('orcamento');
    Route::post('orcamento', 'ProdutosController@orcamentoPost')->name('orcamento.post');

    Route::get('suporte-tecnico', 'SuporteController@index')->name('suporte');
    Route::post('suporte-tecnico', 'SuporteController@post')->name('suporte.post');

    Route::get('parceiros', 'ParceirosController@index')->name('parceiros');
    Route::post('parceiros', 'ParceirosController@post')->name('parceiros.post');

    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');

    Route::get('trabalhe-conosco', 'TrabalheConoscoController@index')->name('trabalhe');
    Route::post('trabalhe-conosco', 'TrabalheConoscoController@post')->name('trabalhe.post');


    // Localização
    Route::get('lang/{idioma?}', function ($idioma = 'pt') {
        if (in_array($idioma, ['pt', 'en', 'es'])) {
            Session::put('locale', $idioma);
        }
        return redirect()->intended();
    })->name('lang');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('produtos.especificacoes', 'ProdutosEspecificacoesController', ['parameters' => ['especificacoes' => 'especificacoes_produtos']]);
		Route::resource('produtos/categorias', 'ProdutosCategoriasController', ['except' => ['create', 'store', 'destroy'], 'parameters' => ['categorias' => 'categorias_produtos']]);
		Route::resource('produtos', 'ProdutosController');
		Route::get('produtos/{produtos}/imagens/clear', [
			'as'   => 'painel.produtos.imagens.clear',
			'uses' => 'ProdutosImagensController@clear'
		]);
        Route::resource('produtos.imagens', 'ProdutosImagensController', ['parameters' => ['imagens' => 'imagens_produtos']]);
        Route::get('produtos/{produtos}/aplicacoes/clear', [
			'as'   => 'painel.produtos.aplicacoes.clear',
			'uses' => 'ProdutosAplicacoesController@clear'
		]);
        Route::resource('produtos.aplicacoes', 'ProdutosAplicacoesController', ['parameters' => ['aplicacoes' => 'aplicacoes_produtos']]);
        Route::get('produtos/{produtos}/catalogo/delete/{lang}', 'ProdutosController@deleteCatalogo')->name('painel.produtos.deleteCatalogo');

        Route::get('parceiros/recebidos/{parceiros_recebidos}/toggle', ['as' => 'painel.parceiros.recebidos.toggle', 'uses' => 'ParceirosRecebidosController@toggle']);
        Route::resource('parceiros/recebidos', 'ParceirosRecebidosController', ['parameters' => ['recebidos' => 'parceiros_recebidos']]);
        Route::resource('parceiros', 'ParceirosController', ['only' => ['index', 'update']]);

		Route::resource('faq', 'FaqController');
        Route::resource('assuntos', 'AssuntosController');

        Route::get('suporte-tecnico/recebidos/{suporte_recebidos}/toggle', ['as' => 'painel.suporte-tecnico.recebidos.toggle', 'uses' => 'SuporteTecnicoRecebidosController@toggle']);
        Route::resource('suporte-tecnico/recebidos', 'SuporteTecnicoRecebidosController', ['parameters' => ['recebidos' => 'suporte_recebidos']]);
		Route::resource('suporte-tecnico', 'SuporteTecnicoController', ['only' => ['index', 'update']]);

        Route::resource('galeria', 'GaleriaController');
		Route::get('galeria/{galeria}/imagens/clear', [
			'as'   => 'painel.galeria.imagens.clear',
			'uses' => 'GaleriaImagensController@clear'
		]);
		Route::resource('galeria.imagens', 'GaleriaImagensController', ['parameters' => ['imagens' => 'imagens_galeria']]);

        Route::resource('cd-logistico', 'CdLogisticoController', ['only' => ['index', 'update']]);
		Route::resource('institucional', 'InstitucionalController', ['only' => ['index', 'update']]);

        Route::resource('depoimentos', 'DepoimentosController');
		Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
		Route::resource('chamadas', 'ChamadasController');
		Route::resource('banners', 'BannersController');
		Route::resource('areas-de-interesse', 'AreasDeInteresseController');

        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');

        Route::get('contato/trabalhe-conosco/{trabalhe_conosco}/toggle', ['as' => 'painel.contato.trabalhe-conosco.toggle', 'uses' => 'TrabalheConoscoController@toggle']);
        Route::resource('contato/trabalhe-conosco', 'TrabalheConoscoController');

        Route::resource('contato', 'ContatoController');

        Route::resource('newsletter', 'NewsletterController', [
            'only' => ['index', 'destroy']
        ]);
        Route::get('newsletter/exportar', 'NewsletterController@exportar')->name('painel.newsletter.exportar');

        Route::get('orcamentos/{orcamentos}/toggle', ['as' => 'painel.orcamentos.toggle', 'uses' => 'OrcamentosController@toggle']);
        Route::resource('orcamentos', 'OrcamentosController');

        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/AreasDeInteresseController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\AreasDeInteresseRequest;
use App\Http\Controllers\Controller;

use App\Models\AreaDeInteresse;

class AreasDeInteresseController extends Controller
{
    public function index()
    {
        $registros = AreaDeInteresse::ordenados()->get();

        return view('painel.areas-de-interesse.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.areas-de-interesse.create');
    }

    public function store(AreasDeInteresseRequest $request)
    {
        try {

            $input = $request->all();

            AreaDeInteresse::create($input);

            return redirect()->route('painel.areas-de-interesse.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(AreaDeInteresse $registro)
    {
        return view('painel.areas-de-interesse.edit', compact('registro'));
    }

    public function update(AreasDeInteresseRequest $request, AreaDeInteresse $registro)
    {
        try {

            $input = $request->all();

            $registro->update($input);

            return redirect()->route('painel.areas-de-interesse.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(AreaDeInteresse $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.areas-de-interesse.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/AssuntosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\AssuntosRequest;
use App\Http\Controllers\Controller;

use App\Models\Assunto;

class AssuntosController extends Controller
{
    public function index()
    {
        $registros = Assunto::ordenados()->get();

        return view('painel.assuntos.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.assuntos.create');
    }

    public function store(AssuntosRequest $request)
    {
        try {

            $input = $request->all();

            Assunto::create($input);

            return redirect()->route('painel.assuntos.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Assunto $registro)
    {
        return view('painel.assuntos.edit', compact('registro'));
    }

    public function update(AssuntosRequest $request, Assunto $registro)
    {
        try {

            $input = $request->all();

            $registro->update($input);

            return redirect()->route('painel.assuntos.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Assunto $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.assuntos.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/CdLogisticoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\CdLogisticoRequest;
use App\Http\Controllers\Controller;

use App\Models\CdLogistico;

class CdLogisticoController extends Controller
{
    public function index()
    {
        $registro = CdLogistico::first();

        return view('painel.cd-logistico.edit', compact('registro'));
    }

    public function update(CdLogisticoRequest $request, CdLogistico $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_1'])) $input['imagem_1'] = CdLogistico::upload_imagem_1();
            if (isset($input['imagem_2'])) $input['imagem_2'] = CdLogistico::upload_imagem_2();

            $registro->update($input);

            return redirect()->route('painel.cd-logistico.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ChamadasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ChamadasRequest;
use App\Http\Controllers\Controller;

use App\Models\Chamada;

class ChamadasController extends Controller
{
    public function index()
    {
        $registros = Chamada::ordenados()->get();

        return view('painel.chamadas.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.chamadas.create');
    }

    public function store(ChamadasRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Chamada::upload_imagem();

            Chamada::create($input);

            return redirect()->route('painel.chamadas.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Chamada $registro)
    {
        return view('painel.chamadas.edit', compact('registro'));
    }

    public function update(ChamadasRequest $request, Chamada $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Chamada::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.chamadas.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Chamada $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.chamadas.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ConfiguracoesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ConfiguracoesRequest;
use App\Http\Controllers\Controller;

use App\Models\Configuracoes;

class ConfiguracoesController extends Controller
{
    public function index()
    {
        $registro = Configuracoes::first();

        return view('painel.configuracoes.edit', compact('registro'));
    }

    public function update(ConfiguracoesRequest $request, Configuracoes $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_de_compartilhamento'])) $input['imagem_de_compartilhamento'] = Configuracoes::upload_imagem_de_compartilhamento();

            $registro->update($input);

            return redirect()->route('painel.configuracoes.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/depoimentos/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Depoimentos /</small> Adicionar Depoimento</h2>
    </legend>

    {!! Form::open(['route' => 'painel.depoimentos.store', 'files' => true]) !!}

        @include('painel.depoimentos.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/depoimentos/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Depoimentos /</small> Editar Depoimento</h2>
    </legend>

    {!! Form::model($registro, [
        'route'  => ['painel.depoimentos.update', $registro->id],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.depoimentos.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/depoimentos/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('nome', 'Nome') !!}
    {!! Form::text('nome', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('empresa', 'Empresa') !!}
    {!! Form::text('empresa', null, ['class' => 'form-control']) !!}
</div>

<div class="well form-group">
    {!! Form::label('imagem', 'Imagem') !!}
@if($submitText == 'Alterar')
    <img src="{{ url('assets/img/depoimentos/'.$registro->imagem) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
@endif
    {!! Form::file('imagem', ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('texto_pt', 'Texto [PT]') !!}
    {!! Form::textarea('texto_pt', null, ['class' => 'form-control ckeditor', 'data-editor' => 'cleanBr']) !!}
</div>

<div class="form-group">
    {!! Form::label('texto_en', 'Texto [EN]') !!}
    {!! Form::textarea('texto_en', null, ['class' => 'form-control ckeditor', 'data-editor' => 'cleanBr']) !!}
</div>

<div class="form-group">
    {!! Form::label('texto_es', 'Texto [ES]') !!}
    {!! Form::textarea('texto_es', null, ['class' => 'form-control ckeditor', 'data-editor' => 'cleanBr']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.depoimentos.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/depoimentos/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <legend>
        <h2>
            Depoimentos
            <a href="{{ route('painel.depoimentos.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Depoimento</a>
        </h2>
    </legend>


    @if(!count($registros))
    <div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="depoimentos">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Nome</th>
                <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)
            <tr class="tr-row" id="{{ $registro->id }}">
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                <td>{{ $registro->nome }}</td>
                <td class="crud-actions">
                    {!! Form::open([
                        'route'  => ['painel.depoimentos.destroy', $registro->id],
                        'method' => 'delete'
                    ]) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.depoimentos.edit', $registro->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @endif

@endsection