laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::post('newsletter', 'HomeController@newsletter')->name('newsletter');
    Route::get('busca', 'HomeController@busca')->name('busca');

    Route::get('a-america-uv/institucional', 'EmpresaController@institucional')->name('empresa.institucional');
    Route::get('a-america-uv/cd-logistico', 'EmpresaController@cdLogistico')->name('empresa.cd-logistico');
    Route::get('a-america-uv/galeria', 'EmpresaController@galeria')->name('empresa.galeria');
    Route::get('a-america-uv/galeria/{galeria_slug}', 'EmpresaController@galeriaShow')->name('empresa.galeria.show');

    Route::get('tecnologias/{categoria_slug}', 'ProdutosController@tecnologias')->name('tecnologias');
    Route::get('tecnologias/{categoria_slug}/{produto_slug}', 'ProdutosController@tecnologiasShow')->name('tecnologias.show');

    Route::get('tinta-digital-uv-led-hnd-ink', 'ProdutosController@tintas')->name('tinta-digital-uv-led-hnd-ink');
    Route::get('tinta-digital-uv-led-hnd-ink/{produto_slug}', 'ProdutosController@tintasShow')->name('tinta-digital-uv-led-hnd-ink.show');

    Route::get('materiais', 'ProdutosController@materiais')->name('materiais');
    Route::get('materiais/{produto_slug}', 'ProdutosController@materiaisShow')->name('materiais.show');

    Route::get('orcamento/{produto_slug}', 'ProdutosController@orcamento')->name('orcamento');
    Route::post('orcamento', 'ProdutosController@orcamentoPost')->name('orcamento.post');

    Route::get('suporte-tecnico', 'SuporteController@index')->name('suporte');
    Route::post('suporte-tecnico', 'SuporteController@post')->name('suporte.post');

    Route::get('parceiros', 'ParceirosController@index')->name('parceiros');
    Route::post('parceiros', 'ParceirosController@post')->name('parceiros.post');

    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');

    Route::get('trabalhe-conosco', 'TrabalheConoscoController@index')->name('trabalhe');
    Route::post('trabalhe-conosco', 'TrabalheConoscoController@post')->name('trabalhe.post');


    // Localização
    Route::get('lang/{idioma?}', function ($idioma = 'pt') {
        if (in_array($idioma, ['pt', 'en', 'es'])) {
            Session::put('locale', $idioma);
        }
        return redirect()->intended();
    })->name('lang');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('produtos.especificacoes', 'ProdutosEspecificacoesController', ['parameters' => ['especificacoes' => 'especificacoes_produtos']]);
		Route::resource('produtos/categorias', 'ProdutosCategoriasController', ['except' => ['create', 'store', 'destroy'], 'parameters' => ['categorias' => 'categorias_produtos']]);
		Route::resource('produtos', 'ProdutosController');
		Route::get('produtos/{produtos}/imagens/clear', [
			'as'   => 'painel.produtos.imagens.clear',
			'uses' => 'ProdutosImagensController@clear'
		]);
        Route::resource('produtos.imagens', 'ProdutosImagensController', ['parameters' => ['imagens' => 'imagens_produtos']]);
        Route::get('produtos/{produtos}/aplicacoes/clear', [
			'as'   => 'painel.produtos.aplicacoes.clear',
			'uses' => 'ProdutosAplicacoesController@clear'
		]);
        Route::resource('produtos.aplicacoes', 'ProdutosAplicacoesController', ['parameters' => ['aplicacoes' => 'aplicacoes_produtos']]);
        Route::get('produtos/{produtos}/catalogo/delete/{lang}', 'ProdutosController@deleteCatalogo')->name('painel.produtos.deleteCatalogo');

        Route::get('parceiros/recebidos/{parceiros_recebidos}/toggle', ['as' => 'painel.parceiros.recebidos.toggle', 'uses' => 'ParceirosRecebidosController@toggle']);
        Route::resource('parceiros/recebidos', 'ParceirosRecebidosController', ['parameters' => ['recebidos' => 'parceiros_recebidos']]);
        Route::resource('parceiros', 'ParceirosController', ['only' => ['index', 'update']]);

		Route::resource('faq', 'FaqController');
        Route::resource('assuntos', 'AssuntosController');

        Route::get('suporte-tecnico/recebidos/{suporte_recebidos}/toggle', ['as' => 'painel.suporte-tecnico.recebidos.toggle', 'uses' => 'SuporteTecnicoRecebidosController@toggle']);
        Route::resource('suporte-tecnico/recebidos', 'SuporteTecnicoRecebidosController', ['parameters' => ['recebidos' => 'suporte_recebidos']]);
		Route::resource('suporte-tecnico', 'SuporteTecnicoController', ['only' => ['index', 'update']]);

        Route::resource('galeria', 'GaleriaController');
		Route::get('galeria/{galeria}/imagens/clear', [
			'as'   => 'painel.galeria.imagens.clear',
			'uses' => 'GaleriaImagensController@clear'
		]);
		Route::resource('galeria.imagens', 'GaleriaImagensController', ['parameters' => ['imagens' => 'imagens_galeria']]);

        Route::resource('cd-logistico', 'CdLogisticoController', ['only' => ['index', 'update']]);
		Route::resource('institucional', 'InstitucionalController', ['only' => ['index', 'update']]);

        Route::resource('depoimentos', 'DepoimentosController');
		Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
		Route::resource('chamadas', 'ChamadasController');
		Route::resource('banners', 'BannersController');
		Route::resource('areas-de-interesse', 'AreasDeInteresseController');

        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');

        Route::get('contato/trabalhe-conosco/{trabalhe_conosco}/toggle', ['as' => 'painel.contato.trabalhe-conosco.toggle', 'uses' => 'TrabalheConoscoController@toggle']);
        Route::resource('contato/trabalhe-conosco', 'TrabalheConoscoController');

        Route::resource('contato', 'ContatoController');

        Route::resource('newsletter', 'NewsletterController', [
            'only' => ['index', 'destroy']
        ]);
        Route::get('newsletter/exportar', 'NewsletterController@exportar')->name('painel.newsletter.exportar');

        Route::get('orcamentos/{orcamentos}/toggle', ['as' => 'painel.orcamentos.toggle', 'uses' => 'OrcamentosController@toggle']);
        Route::resource('orcamentos', 'OrcamentosController');

        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/AreasDeInteresseController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\AreasDeInteresseRequest;
use App\Http\Controllers\Controller;

use App\Models\AreaDeInteresse;

class AreasDeInteresseController extends Controller
{
    public function index()
    {
        $registros = AreaDeInteresse::ordenados()->get();

        return view('painel.areas-de-interesse.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.areas-de-interesse.create');
    }

    public function store(AreasDeInteresseRequest $request)
    {
        try {

            $input = $request->all();

            AreaDeInteresse::create($input);

            return redirect()->route('painel.areas-de-interesse.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(AreaDeInteresse $registro)
    {
        return view('painel.areas-de-interesse.edit', compact('registro'));
    }

    public function update(AreasDeInteresseRequest $request, AreaDeInteresse $registro)
    {
        try {

            $input = $request->all();

            $registro->update($input);

            return redirect()->route('painel.areas-de-interesse.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(AreaDeInteresse $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.areas-de-interesse.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/AssuntosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\AssuntosRequest;
use App\Http\Controllers\Controller;

use App\Models\Assunto;

class AssuntosController extends Controller
{
    public function index()
    {
        $registros = Assunto::ordenados()->get();

        return view('painel.assuntos.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.assuntos.create');
    }

    public function store(AssuntosRequest $request)
    {
        try {

            $input = $request->all();

            Assunto::create($input);

            return redirect()->route('painel.assuntos.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Assunto $registro)
    {
        return view('painel.assuntos.edit', compact('registro'));
    }

    public function update(AssuntosRequest $request, Assunto $registro)
    {
        try {

            $input = $request->all();

            $registro->update($input);

            return redirect()->route('painel.assuntos.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Assunto $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.assuntos.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/CdLogisticoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\CdLogisticoRequest;
use App\Http\Controllers\Controller;

use App\Models\CdLogistico;

class CdLogisticoController extends Controller
{
    public function index()
    {
        $registro = CdLogistico::first();

        return view('painel.cd-logistico.edit', compact('registro'));
    }

    public function update(CdLogisticoRequest $request, CdLogistico $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_1'])) $input['imagem_1'] = CdLogistico::upload_imagem_1();
            if (isset($input['imagem_2'])) $input['imagem_2'] = CdLogistico::upload_imagem_2();

            $registro->update($input);

            return redirect()->route('painel.cd-logistico.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ChamadasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ChamadasRequest;
use App\Http\Controllers\Controller;

use App\Models\Chamada;

class ChamadasController extends Controller
{
    public function index()
    {
        $registros = Chamada::ordenados()->get();

        return view('painel.chamadas.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.chamadas.create');
    }

    public function store(ChamadasRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Chamada::upload_imagem();

            Chamada::create($input);

            return redirect()->route('painel.chamadas.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Chamada $registro)
    {
        return view('painel.chamadas.edit', compact('registro'));
    }

    public function update(ChamadasRequest $request, Chamada $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Chamada::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.chamadas.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Chamada $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.chamadas.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ConfiguracoesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ConfiguracoesRequest;
use App\Http\Controllers\Controller;

use App\Models\Configuracoes;

class ConfiguracoesController extends Controller
{
    public function index()
    {
        $registro = Configuracoes::first();

        return view('painel.configuracoes.edit', compact('registro'));
    }

    public function update(ConfiguracoesRequest $request, Configuracoes $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_de_compartilhamento'])) $input['imagem_de_compartilhamento'] = Configuracoes::upload_imagem_de_compartilhamento();

            $registro->update($input);

            return redirect()->route('painel.configuracoes.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/header.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url('/') }}">{{ config('app.name') }}</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            @include('painel.common.nav')

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown @if(Tools::routeIs(['painel.usuarios*', 'painel.configuracoes*'])) active @endif">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li @if(Tools::routeIs('painel.configuracoes*')) class="active" @endif>
                            <a href="{{ route('painel.configuracoes.index') }}">Configurações</a>
                        </li>
                        <li @if(Tools::routeIs('painel.usuarios*')) class="active" @endif>
                            <a href="{{ route('painel.usuarios.index') }}">Usuários</a>
                        </li>
                        <li><a href="{{ route('logout') }}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">
    <li class="dropdown @if(Tools::routeIs(['painel.home*', 'painel.banners*', 'painel.chamadas*', 'painel.depoimentos*'])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Home
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.home*')) class="active" @endif>
                <a href="{{ route('painel.home.index') }}">Home</a>
            </li>
            <li @if(Tools::routeIs('painel.banners*')) class="active" @endif>
                <a href="{{ route('painel.banners.index') }}">Banners</a>
            </li>
            <li @if(Tools::routeIs('painel.chamadas*')) class="active" @endif>
                <a href="{{ route('painel.chamadas.index') }}">Chamadas</a>
            </li>
            <li @if(Tools::routeIs('painel.depoimentos*')) class="active" @endif>
                <a href="{{ route('painel.depoimentos.index') }}">Depoimentos</a>
            </li>
        </ul>
    </li>
    <li class="dropdown @if(Tools::routeIs(['painel.institucional*', 'painel.cd-logistico*', 'painel.galeria*'])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            America UV
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.institucional*')) class="active" @endif>
                <a href="{{ route('painel.institucional.index') }}">Institucional</a>
            </li>
            <li @if(Tools::routeIs('painel.cd-logistico*')) class="active" @endif>
                <a href="{{ route('painel.cd-logistico.index') }}">CD Logístico</a>
            </li>
            <li @if(Tools::routeIs('painel.galeria*')) class="active" @endif>
                <a href="{{ route('painel.galeria.index') }}">Galeria</a>
            </li>
        </ul>
    </li>
    <li @if(Tools::routeIs('painel.produtos*')) class="active" @endif>
		<a href="{{ route('painel.produtos.index') }}">Produtos</a>
	</li>
    <li class="dropdown @if(Tools::routeIs(['painel.suporte-tecnico.index', 'painel.assuntos*', 'painel.faq*', 'painel.suporte-tecnico.recebidos*'])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Suporte Técnico
            @if($suporteNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $suporteNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.suporte-tecnico.index')) class="active" @endif>
                <a href="{{ route('painel.suporte-tecnico.index') }}">Suporte Técnico</a>
            </li>
            <li @if(Tools::routeIs('painel.assuntos*')) class="active" @endif>
                <a href="{{ route('painel.assuntos.index') }}">Assuntos</a>
            </li>
            <li @if(Tools::routeIs('painel.faq*')) class="active" @endif>
                <a href="{{ route('painel.faq.index') }}">FAQ</a>
            </li>
            <li class="divider"></li>
            <li @if(Tools::routeIs('painel.suporte-tecnico.recebidos*')) class="active" @endif>
                <a href="{{ route('painel.suporte-tecnico.recebidos.index') }}">
                    Solicitações Recebidas
                    @if($suporteNaoLidos >= 1)
                    <span class="label label-success" style="margin-left:3px;">{{ $suporteNaoLidos }}</span>
                    @endif
                </a>
            </li>
        </ul>
    </li>
    <li class="dropdown @if(Tools::routeIs(['painel.parceiros.index', 'painel.parceiros.recebidos*'])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Parceiros
            @if($parceirosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $parceirosNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.parceiros.index')) class="active" @endif>
                <a href="{{ route('painel.parceiros.index') }}">Parceiros</a>
            </li>
            <li class="divider"></li>
            <li @if(Tools::routeIs('painel.parceiros.recebidos*')) class="active" @endif>
                <a href="{{ route('painel.parceiros.recebidos.index') }}">
                    Solicitações Recebidas
                    @if($parceirosNaoLidos >= 1)
                    <span class="label label-success" style="margin-left:3px;">{{ $parceirosNaoLidos }}</span>
                    @endif
                </a>
            </li>
        </ul>
    </li>
    <li class="dropdown @if(Tools::routeIs(['painel.contato*', 'painel.areas-de-interesse*'])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Contato
            @if($contatosNaoLidos + $curriculosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos + $curriculosNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.contato.index')) class="active" @endif>
                <a href="{{ route('painel.contato.index') }}">Informações de Contato</a>
            </li>
            <li class="divider"></li>
            <li @if(Tools::routeIs('painel.contato.recebidos*')) class="active" @endif>
                <a href="{{ route('painel.contato.recebidos.index') }}">
                    Contatos Recebidos
                    @if($contatosNaoLidos >= 1)
                    <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                    @endif
                </a>
            </li>
            <li @if(Tools::routeIs('painel.contato.trabalhe-conosco*')) class="active" @endif>
                <a href="{{ route('painel.contato.trabalhe-conosco.index') }}">
                    Trabalhe Conosco
                    @if($curriculosNaoLidos >= 1)
                    <span class="label label-success" style="margin-left:3px;">{{ $curriculosNaoLidos }}</span>
                    @endif
                </a>
            </li>
            <li class="divider"></li>
            <li @if(Tools::routeIs('painel.areas-de-interesse*')) class="active" @endif>
                <a href="{{ route('painel.areas-de-interesse.index') }}">Áreas de Interesse <small>(Trabalhe Conosco)</small></a>
            </li>
        </ul>
    </li>
    <li @if(Tools::routeIs('painel.orcamentos*')) class="active" @endif>
        <a href="{{ route('painel.orcamentos.index') }}">
            Orçamentos
            @if($orcamentosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $orcamentosNaoLidos }}</span>
            @endif
        </a>
    </li>
    <li @if(Tools::routeIs('painel.newsletter*')) class="active" @endif>
        <a href="{{ route('painel.newsletter.index') }}">Newsletter</a>
    </li>
</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ config('app.name') }} - Painel Administrativo</title>

    <link rel="stylesheet" href="{{ asset('assets/vendor/bootswatch-dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/jquery-ui/themes/cupertino/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/vendor.painel.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/painel.css') }}">
</head>
<body>
    @include('painel.common.header')

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="{{ asset('assets/vendor/jquery/dist/jquery.min.js') }}"><\/script>')</script>
    <script src="{{ asset('assets/vendor/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/js/vendor.painel.js') }}"></script>
    <script src="{{ asset('assets/js/painel.js') }}"></script>
</body>
</html>